name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      
      - name: Build And Deploy
  id: builddeploy
  uses: Azure/static-web-apps-deploy@v1
  with:
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    action: "upload"
    app_location: "/frontend"
    api_location: "/api"
    output_location: "build"
    env: |
      COSMOSDB_ENDPOINT=${{ secrets.COSMOSDB_ENDPOINT }}
      COSMOSDB_KEY=${{ secrets.COSMOSDB_KEY }}
      COSMOSDB_DATABASE=${{ secrets.COSMOSDB_DATABASE }}
      COSMOSDB_CONTAINER_USERS=${{ secrets.COSMOSDB_CONTAINER_USERS }}
      COSMOSDB_CONTAINER_VOTES=${{ secrets.COSMOSDB_CONTAINER_VOTES }}
        
      - name: Run API tests
        run: |
          cd api
          npm install
          npm test

          